version: "3.9"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $APPDATA/jellyfin:/config
      - $MEDIA:/data
    ports:
      - 8096:8096
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:lidarr
      - TP_THEME=$TP_THEME
    volumes:
      - $APPDATA/lidarr:/config
      - $MUSIC:/music
      - $DOWNLOADS:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
    
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $APPDATA/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped

  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - fpm="true"
    volumes:
      - $APPDATA/organizr:/config
    ports:
      - 80:80
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:prowlarr
      - TP_THEME=$TP_THEME
    volumes:
      - $APPDATA/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - WEBUI_PORT=8080
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:qbittorrent
      - TP_THEME=$TP_THEME
    volumes:
      - $APPDATA/qbittorrent:/config
      - $DOWNLOADS:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
      - TP_THEME=$TP_THEME
    volumes:
      - $APPDATA/radarr:/config
      - $MOVIES:/movies
      - $DOWNLOADS:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:readarr
      - TP_THEME=$TP_THEME
    volumes:
      - $APPDATA/readarr:/config
      - $BOOKS:/books
      - $DOWNLOADS:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
      - TP_THEME=$TP_THEME
    volumes:
      - $APPDATA/sonarr:/config
      - $TVSHOWS:/tv
      - $DOWNLOADS:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $APPDATA/tubesync:/config
      - $MEDIA:/downloads
    ports:
      - 4848:4848
    restart: unless-stopped
