version: "3.9"

services:
  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - fpm="true"
    volumes:
      - $APPDATA/organizr:/config
    ports:
      - 80:80
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $APPDATA/jellyfin:/config
      - ./media/tvseries:/data/tvshows
      - $MOVIES:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped

  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $APPDATA/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
      - TP_THEME=$TP_THEME
    volumes:
      - $APPDATA/radarr:/config
      - $MOVIES:/movies
      - $DOWNLOADS:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - WEBUI_PORT=8080
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:qbittorrent
      - TP_THEME=$TP_THEME
    volumes:
      - $APPDATA/qbittorrent:/config
      - $DOWNLOADS:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:prowlarr
      - TP_THEME=$TP_THEME
    volumes:
      - $APPDATA/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
