version: "3.9"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - ./appdata/jellyfin:/config
      - ./media/tvseries:/data/tvshows
      - ./media/movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped
